version: "3.9"

services:
  web:
    build: ./web-app
    depends_on:
      - api
    volumes:
      - ./web-app/nginx-templates:/etc/nginx/templates
    ports:
      - 8080:80
    environment:
      - API_HOST=api
      - API_PORT=4000
  api:
    build: ./urlshortner_api
    depends_on:
      - db
    ports:
      - 4001:4000
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_PASS=${POSTGRES_PASSWORD}
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_URL=${URLSHORTNER_DATABASE_URL}
    env_file:
      - ./urlshortner_api/prod.env
  db:
    image: "postgres:alpine"
    volumes:
      - ./urlshortner_api/data/prod_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
