version: "3.9"

services:
  db:
    image: "postgres:alpine"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  # api:
  #   build: .
  #   depends_on:
  #     - db
  #   ports:
  #     - 4000:4000
  #   environment:
  #     - MIX_ENV=dev